site_name: Grupo 07
docs_dir: ./docs
repo_url: https://github.com/UnB-IHC/IHC-2025.2-Grupo7
repo_name: IHC-2025.2-Grupo7

theme:
  name: material
  language: pt-BR
  logo: assets/logo_oseb.svg
  favicon: assets/logo_oseb.svg
  palette:
    # Paleta para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - navigation.tabs # <-- ADICIONE ESTA LINHA
    - content.code.copy
    - content.action.edit
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js
  - javascripts/charts.js

nav:
  - Home: index.md
  - Design: projeto/design.md
  - Desenvolvimento Web: projeto/desenvolvimentoweb.md
  - Geração de Conteúdo: projeto/geracaodeconteudo
  - Gestão do Projeto: projeto/gestaodeprojetos.md 
  - Site Melhorado: projeto/site-melhorado.md
  - Ferramentas e Referências: 
        - Ferramenta: projeto/ferramentas.md
        - Outras recomendações: projeto/recomendacoes.md
  
